name: Lamy
options:
  bundleIdPrefix: com.dstotijn.lamy
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.2"

settings:
  base:
    SWIFT_VERSION: "6.0"

targets:
  Lamy:
    type: application
    platform: iOS
    sources: [Lamy]
    dependencies:
      - target: LamyShared
      - target: LamyKeyboard
    settings:
      base:
        INFOPLIST_FILE: Lamy/Info.plist
        CODE_SIGN_ENTITLEMENTS: Lamy/Lamy.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.dstotijn.lamy
    entitlements:
      path: Lamy/Lamy.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.dstotijn.lamy

  LamyKeyboard:
    type: app-extension
    platform: iOS
    sources: [LamyKeyboard]
    dependencies:
      - target: LamyShared
    settings:
      base:
        INFOPLIST_FILE: LamyKeyboard/Info.plist
        CODE_SIGN_ENTITLEMENTS: LamyKeyboard/LamyKeyboard.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.dstotijn.lamy.keyboard
    entitlements:
      path: LamyKeyboard/LamyKeyboard.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.dstotijn.lamy

  LamyShared:
    type: framework
    platform: iOS
    sources: [LamyShared/Sources]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dstotijn.lamy.shared
        GENERATE_INFOPLIST_FILE: YES

  LamyTests:
    type: bundle.unit-test
    platform: iOS
    sources: [LamyTests]
    dependencies:
      - target: Lamy
      - target: LamyShared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dstotijn.lamy.tests
        GENERATE_INFOPLIST_FILE: YES
